data:
  raw_root: /data1/common_data/RoboTwin2.0_640_480/dataset
  index_root: outputs/wovr/robotwin_subset_2tasks_16episodes
  width: 640
  height: 480
  fps: 30

action:
  representation: normalized_absolute_ee_pose_euler
  dim: 14
  rotation_representation: euler_xyz
  rotation_unit: radian
  statistics_path: /data1/sunyang/datasets/RoboTwin2.0_lerobot/stat.json

model:
  dit_paths:
    - /data1/sunyang/models/modelscope/hub/models/Wan-AI/Wan2___2-TI2V-5B/diffusion_pytorch_model-00001-of-00003.safetensors
    - /data1/sunyang/models/modelscope/hub/models/Wan-AI/Wan2___2-TI2V-5B/diffusion_pytorch_model-00002-of-00003.safetensors
    - /data1/sunyang/models/modelscope/hub/models/Wan-AI/Wan2___2-TI2V-5B/diffusion_pytorch_model-00003-of-00003.safetensors
  vae_path: /data1/sunyang/models/modelscope/hub/models/Wan-AI/Wan2___2-TI2V-5B/Wan2.2_VAE.pth
  checkpoint_root: outputs/wovr/train_2tasks_16episodes_134epochs_sequential_chunks_normalized_absolute_euler_action_640x480
  checkpoint_epochs:
    - 133
  torch_dtype: bfloat16
  device: cuda:0

inference:
  num_samples: 16
  num_inference_steps: 5
  cfg_scale: 1.0
  tiled: false
  output_root: outputs/wovr/infer_2tasks_16episodes_134epochs_sequential_chunks_normalized_absolute_euler_action_640x480
